# Generated by Django 4.2 on 2023-12-09 22:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cash_machine", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="item",
            name="price",
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name="item",
            name="title",
            field=models.CharField(max_length=100),
        ),
    ]
